events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        error_page 404 /404.html;

        location = /404.html {
            root /usr/share/nginx/html;
            internal;
        }

        # Servir archivos estáticos de Django
        location /static/ {
            alias /app/staticfiles/;
        }

        location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
            root /usr/share/nginx/html;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        location = / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ =404;
        }

        location /api/ {
            proxy_pass http://fastapi:8000;
            proxy_set_header Host $host;
            proxy_intercept_errors on;
            error_page 404 = /404.html;
        }

        location /admin/ {
            proxy_pass http://django:8000;
            proxy_set_header Host $host;
            proxy_intercept_errors on;
            error_page 404 = /404.html;
        }
    }
}